export { login, register, getProfile, changePassword } from './auth'
export { getFarmacias, getFarmacia, createFarmacia, updateFarmacia, removeFarmacia } from './farmacias'
export { getProductos, getProducto, createProducto, updateProducto, removeProducto } from './productos'
export { getPedidos, getPedido, createPedido, updateEstado, asignarDronOperador } from './pedidos'
export { getPagos, createPago, confirmarPago } from './pagos'
export { getDrones, getDronesDisponibles, getDron, createDron, updateDron, removeDron } from './drones'
export { getOperadores, getOperador, createOperador, updateOperador, removeOperador } from './operadores'
export { uploadFile } from './upload'
export { getUsuarios, getUsuario, updateUsuario, updateUsuarioEstado, removeUsuario } from './usuarios'
